# Generated by Django 3.1.2 on 2020-10-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
