# Generated by Django 3.1.2 on 2020-10-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201025_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
